"""modify fields to improve cache invalidation

Revision ID: 543b0c11a790
Revises: 24456e322528
Create Date: 2026-07-11 19:01:15.373749

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "543b0c11a790"
down_revision: str | None = "24456e322528"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite-safe: use batch_alter_table so Alembic recreates the table as columns cannot be changed after creation.

    # mediaitems add revision col
    # Step 1: Add column with temporary server default (outside batch)
    op.add_column("mediaitems", sa.Column("revision", sa.Integer(), nullable=False, server_default="0"))
    # Step 2: Remove server default inside batch (table recreation)
    with op.batch_alter_table("mediaitems") as batch_op:
        batch_op.alter_column("revision", existing_type=sa.Integer(), server_default=None, existing_nullable=False)

    # cacheditems add revision col
    op.execute("DELETE FROM cacheditems")  # cached items could have some orphaned elements, to ensure consistency, we clear the cache before

    # Step 1: Add column with temporary server default (outside batch)
    op.add_column("cacheditems", sa.Column("revision", sa.Integer(), nullable=False, server_default="0"))
    # Step 2: Remove server default inside batch (table recreation)
    with op.batch_alter_table("cacheditems") as batch_op:
        batch_op.alter_column("revision", existing_type=sa.Integer(), server_default=None, existing_nullable=False)

    op.drop_column("cacheditems", "created_at")
    op.drop_column("mediaitems", "updated_at")
    op.drop_column("mediaitems", "unprocessed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cacheditems", "revision")
    op.add_column("cacheditems", sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False))
    op.drop_column("mediaitems", "revision")
    op.add_column("mediaitems", sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False))
    op.add_column("mediaitems", sa.Column("unprocessed", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
